# Generated by Django 3.0.3 on 2020-08-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=500)),
                ('headings', models.CharField(max_length=1000)),
                ('highlights', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=1000)),
                ('activity', models.CharField(max_length=2000)),
                ('education', models.CharField(max_length=2000)),
                ('skills', models.CharField(max_length=2000)),
                ('interests', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
